/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera, useAnimations } from "@react-three/drei";
import { useEffect } from 'react';

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/customers_coloriage_reduction.glb"
  );
  const { ref, mixer, names, actions, clips } = useAnimations(animations)
  useEffect(() => {
    actions?.tourner.play()
    actions?.Monter.play()
  })
  return (
    <group ref={ref} {...props} dispose={null}>
      <group name="Scene">
        <group name="BezierCircle" position={[0, 1.05, 0]} scale={5.18} />
        <pointLight
      castShadow
      shadow-mapSize-height={1024}
      shadow-mapSize-width={1024}
 //3500
      shadow-bias={-0.001}
        intensity={0.8}
        decay={2}
        distance={6.58}
        position={[1.53, 1.34, 1.59]}
        rotation={[-0.37, 0.71, 0.25]}
        scale={0.6}
      />
      <pointLight
            castShadow
      shadow-mapSize-height={1024}
      shadow-mapSize-width={1024}
 //3500
      shadow-bias={-0.001}
        intensity={0.8}
        decay={2}
        distance={6.58}
        position={[-1.61, 1.28, 1.61]}
        rotation={[-0.37, -0.73, -0.25]}
        scale={0.57}
      />
      <pointLight
            castShadow
      shadow-mapSize-height={1024}
      shadow-mapSize-width={1024}
 //3500
      shadow-bias={-0.001}
        intensity={0.8}
        decay={2}
        distance={6.58}
        position={[-1.6, 1.28, -1.63]}
        rotation={[-2.76, -0.76, -2.87]}
        scale={0.57}
      />
      <pointLight
            castShadow
      shadow-mapSize-height={1024}
      shadow-mapSize-width={1024}
 //3500
      shadow-bias={-0.001}
        intensity={0.8}
        decay={2}
        distance={6.58}
        position={[1.54, 1.28, -1.64]}
        rotation={[-2.77, 0.74, 2.88]}
        scale={0.57}
      />
