/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/customers_coloriage_reduction.glb"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="BezierCircle" position={[0, 1.05, 0]} scale={5.18} />
        <pointLight
      castShadow
      shadow-mapSize-height={1024}
      shadow-mapSize-width={1024}
 //3500
      shadow-bias={-0.001}
        intensity={0.8}
        decay={2}
        distance={6.58}
        position={[1.53, 1.34, 1.59]}
        rotation={[-0.37, 0.71, 0.25]}
        scale={0.6}
      />
      <pointLight
            castShadow
      shadow-mapSize-height={1024}
      shadow-mapSize-width={1024}
 //3500
      shadow-bias={-0.001}
        intensity={0.8}
        decay={2}
        distance={6.58}
        position={[-1.61, 1.28, 1.61]}
        rotation={[-0.37, -0.73, -0.25]}
        scale={0.57}
      />
      <pointLight
            castShadow
      shadow-mapSize-height={1024}
      shadow-mapSize-width={1024}
 //3500
      shadow-bias={-0.001}
        intensity={0.8}
        decay={2}
        distance={6.58}
        position={[-1.6, 1.28, -1.63]}
        rotation={[-2.76, -0.76, -2.87]}
        scale={0.57}
      />
      <pointLight
            castShadow
      shadow-mapSize-height={1024}
      shadow-mapSize-width={1024}
 //3500
      shadow-bias={-0.001}
        intensity={0.8}
        decay={2}
        distance={6.58}
        position={[1.54, 1.28, -1.64]}
        rotation={[-2.77, 0.74, 2.88]}
        scale={0.57}
      />
        <group name="Cube">
          <mesh
            name="Cube001_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_1.geometry}
            material={materials.BEIGE}
          />
          <mesh
            name="Cube001_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_2.geometry}
            material={materials.ROUGE}
          />
        </group>
        <group name="Cube001" position={[0.99, 0.93, 0]}>
          <mesh
            name="Cube002_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube002_1.geometry}
            material={materials.SAUGE}
          />
          <mesh
            name="Cube002_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube002_2.geometry}
            material={materials["JAUNE FONCE"]}
          />
        </group>
        <group name="Cube019" position={[-1, 0.93, 0]}>
          <mesh
            name="Cube026_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube026_1.geometry}
            material={materials.ROUGE}
          />
          <mesh
            name="Cube026_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube026_2.geometry}
            material={materials.ROUGE}
          />
        </group>
        <group name="Cube020" position={[-0.01, 0.93, -1.04]}>
          <mesh
            name="Cube027_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube027_1.geometry}
            material={materials.BEIGE}
          />
          <mesh
            name="Cube027_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube027_2.geometry}
            material={materials.BLEU}
          />
          <mesh
            name="Cube027_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube027_3.geometry}
            material={materials.GRIS}
          />
        </group>
        <mesh
          name="Cube002"
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={materials.BEIGE}
          position={[0, 0.06, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Cube018"
          castShadow
          receiveShadow
          geometry={nodes.Cube018.geometry}
          material={materials["JAUNE PALE"]}
          position={[-1.72, 0.11, -1.04]}
          scale={[1, 0.11, 1]}
        />
        <group
          name="Guitar_Mixer"
          position={[-0.5, 0.42, -1.21]}
          rotation={[0, 0.67, 0]}
          scale={0.52}
        >
          <mesh
            name="Cube032_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube032_1.geometry}
            material={materials["JAUNE FONCE"]}
          />
          <mesh
            name="Cube032_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube032_2.geometry}
            material={materials["VERT FLASH"]}
          />
          <mesh
            name="Cube032_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube032_3.geometry}
            material={materials.ROUGE}
          />
          <mesh
            name="Cube032_4"
            castShadow
            receiveShadow
            geometry={nodes.Cube032_4.geometry}
            material={materials.MARRON}
          />
          <mesh
            name="Cube032_5"
            castShadow
            receiveShadow
            geometry={nodes.Cube032_5.geometry}
            material={materials.CREME}
          />
          <mesh
            name="Cube032_6"
            castShadow
            receiveShadow
            geometry={nodes.Cube032_6.geometry}
            material={materials.BLEU}
          />
          <mesh
            name="Cube032_7"
            castShadow
            receiveShadow
            geometry={nodes.Cube032_7.geometry}
            material={materials.GRIS}
          />
        </group>
        <group
          name="Black_Amplifier_3"
          position={[-0.48, 0.26, -1.22]}
          rotation={[-Math.PI, 0.8, -Math.PI]}
          scale={0.52}
        >
          <mesh
            name="Cube209"
            castShadow
            receiveShadow
            geometry={nodes.Cube209.geometry}
            material={materials.MARRON}
          />
          <mesh
            name="Cube209_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube209_1.geometry}
            material={materials.CREME}
          />
          <mesh
            name="Cube209_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube209_2.geometry}
            material={materials.NOIR}
          />
        </group>
        <mesh
          name="Bench"
          castShadow
          receiveShadow
          geometry={nodes.Bench.geometry}
          material={materials["BOIS CLAIR"]}
          position={[-0.81, 0.23, -1.74]}
          scale={0.42}
        />
        <group
          name="Cube043"
          position={[-0.23, 1.33, -0.8]}
          rotation={[Math.PI, 0, Math.PI / 2]}
          scale={0.72}
        >
          <mesh
            name="Cube055"
            castShadow
            receiveShadow
            geometry={nodes.Cube055.geometry}
            material={materials["BOIS DIFFUSEUR"]}
          />
          <mesh
            name="Cube055_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube055_1.geometry}
            material={materials.MARRON}
          />
          <mesh
            name="Cube055_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube055_2.geometry}
            material={materials.MARRON}
          />
        </group>
        <group
          name="Cube035"
          position={[-1.17, 1.63, -0.79]}
          rotation={[Math.PI, 0, 0]}
          scale={0.72}
        >
          <mesh
            name="Cube045_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube045_1.geometry}
            material={materials["BOIS DIFFUSEUR"]}
          />
          <mesh
            name="Cube045_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube045_2.geometry}
            material={materials.MARRON}
          />
          <mesh
            name="Cube045_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube045_3.geometry}
            material={materials.MARRON}
          />
        </group>
        <mesh
          name="Cylinder004"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004.geometry}
          material={materials.MARRON}
          position={[-0.98, 1.71, -0.16]}
          scale={[0.78, 1, 1]}
        />
        <group
          name="Cube032"
          position={[-0.76, 1.63, -0.37]}
          rotation={[Math.PI, 0, 0]}
          scale={0.72}
        >
          <mesh
            name="Cube042_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube042_1.geometry}
            material={materials["BOIS DIFFUSEUR"]}
          />
          <mesh
            name="Cube042_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube042_2.geometry}
            material={materials.MARRON}
          />
          <mesh
            name="Cube042_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube042_3.geometry}
            material={materials.MARRON}
          />
        </group>
        <mesh
          name="Cylinder005"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005.geometry}
          material={materials.MARRON}
          position={[-0.55, 1.71, -0.59]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="Object_2"
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials["BOIS CLAIR"]}
          position={[-1, 0.16, -0.83]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.18}
        />
        <mesh
          name="Text002"
          castShadow
          receiveShadow
          geometry={nodes.Text002.geometry}
          material={materials.CREME}
          position={[-1, 1.5, -0.04]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={0.24}
        />
        <group
          name="Cube033"
          position={[-1.18, 1.62, -0.37]}
          rotation={[-Math.PI, -Math.PI / 2, 0]}
          scale={[0.84, 0.85, 0.84]}
        >
          <mesh
            name="Cube043_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube043_1.geometry}
            material={materials["BOIS DIFFUSEUR"]}
          />
          <mesh
            name="Cube043_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube043_2.geometry}
            material={materials.CREME}
          />
          <mesh
            name="Cube043_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube043_3.geometry}
            material={materials.MARRON}
          />
        </group>
        <group
          name="Cube034"
          position={[-0.76, 1.62, -0.79]}
          rotation={[-Math.PI, -Math.PI / 2, 0]}
          scale={[0.84, 0.85, 0.84]}
        >
          <mesh
            name="Cube044"
            castShadow
            receiveShadow
            geometry={nodes.Cube044.geometry}
            material={materials["BOIS DIFFUSEUR"]}
          />
          <mesh
            name="Cube044_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube044_1.geometry}
            material={materials.CREME}
          />
          <mesh
            name="Cube044_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube044_2.geometry}
            material={materials.MARRON}
          />
        </group>
        <group
          name="Cube045"
          position={[-0.24, 0.92, -0.81]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.84, 0.85, 0.84]}
        >
          <mesh
            name="Cube057"
            castShadow
            receiveShadow
            geometry={nodes.Cube057.geometry}
            material={materials["BOIS DIFFUSEUR"]}
          />
          <mesh
            name="Cube057_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube057_1.geometry}
            material={materials.CREME}
          />
          <mesh
            name="Cube057_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube057_2.geometry}
            material={materials.MARRON}
          />
        </group>
        <group
          name="Cube048"
          position={[-0.23, 0.92, -1.22]}
          rotation={[Math.PI, 0, Math.PI / 2]}
          scale={0.72}
        >
          <mesh
            name="Cube060"
            castShadow
            receiveShadow
            geometry={nodes.Cube060.geometry}
            material={materials["BOIS DIFFUSEUR"]}
          />
          <mesh
            name="Cube060_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube060_1.geometry}
            material={materials.MARRON}
          />
          <mesh
            name="Cube060_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube060_2.geometry}
            material={materials.MARRON}
          />
        </group>
        <group
          name="Cube049"
          position={[-0.23, 1.33, -1.64]}
          rotation={[Math.PI, 0, Math.PI / 2]}
          scale={0.72}
        >
          <mesh
            name="Cube062"
            castShadow
            receiveShadow
            geometry={nodes.Cube062.geometry}
            material={materials["BOIS DIFFUSEUR"]}
          />
          <mesh
            name="Cube062_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube062_1.geometry}
            material={materials.MARRON}
          />
          <mesh
            name="Cube062_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube062_2.geometry}
            material={materials.MARRON}
          />
        </group>
        <group
          name="Cube038"
          position={[-0.24, 1.34, -1.22]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.84, 0.85, 0.84]}
        >
          <mesh
            name="Cube063"
            castShadow
            receiveShadow
            geometry={nodes.Cube063.geometry}
            material={materials["BOIS DIFFUSEUR"]}
          />
          <mesh
            name="Cube063_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube063_1.geometry}
            material={materials.CREME}
          />
          <mesh
            name="Cube063_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube063_2.geometry}
            material={materials.MARRON}
          />
        </group>
        <group
          name="Cube039"
          position={[-0.24, 0.92, -1.64]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.84, 0.85, 0.84]}
        >
          <mesh
            name="Cube064"
            castShadow
            receiveShadow
            geometry={nodes.Cube064.geometry}
            material={materials["BOIS DIFFUSEUR"]}
          />
          <mesh
            name="Cube064_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube064_1.geometry}
            material={materials.CREME}
          />
          <mesh
            name="Cube064_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube064_2.geometry}
            material={materials.MARRON}
          />
        </group>
        <group
          name="Cymbal_1"
          position={[-1.05, 0.52, -0.46]}
          rotation={[3.12, 1.51, -3.1]}
          scale={0.68}
        >
          <mesh
            name="Cylinder027"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder027.geometry}
            material={materials.MARRON}
          />
          <mesh
            name="Cylinder027_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder027_1.geometry}
            material={materials["JAUNE FONCE"]}
          />
          <mesh
            name="Cylinder027_2"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder027_2.geometry}
            material={materials.CREME}
          />
        </group>
        <mesh
          name="Cylinder006"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006.geometry}
          material={materials.MARRON}
          position={[-1, 1.38, -0.06]}
          scale={[0.71, 1, 1]}
        />
        <group
          name="Black_Amplifier_4"
          position={[-0.34, 0.28, -1.68]}
          rotation={[-Math.PI, 0.07, -Math.PI]}
          scale={0.59}
        >
          <mesh
            name="Cube210"
            castShadow
            receiveShadow
            geometry={nodes.Cube210.geometry}
            material={materials.MARRON}
          />
          <mesh
            name="Cube210_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube210_1.geometry}
            material={materials.NOIR}
          />
          <mesh
            name="Cube210_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube210_2.geometry}
            material={materials.CREME}
          />
        </group>
        <group
          name="Small_Amplifier_1"
          position={[-0.37, 0.48, -1.64]}
          rotation={[Math.PI, -0.14, Math.PI]}
          scale={0.59}
        >
          <mesh
            name="Cube211"
            castShadow
            receiveShadow
            geometry={nodes.Cube211.geometry}
            material={materials.NOIR}
          />
          <mesh
            name="Cube211_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube211_1.geometry}
            material={materials["JAUNE FONCE"]}
          />
          <mesh
            name="Cube211_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube211_2.geometry}
            material={materials.GRIS}
          />
          <mesh
            name="Cube211_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube211_3.geometry}
            material={materials.MARRON}
          />
          <mesh
            name="Cube211_4"
            castShadow
            receiveShadow
            geometry={nodes.Cube211_4.geometry}
            material={materials.CREME}
          />
          <mesh
            name="Cube211_5"
            castShadow
            receiveShadow
            geometry={nodes.Cube211_5.geometry}
            material={materials.ROUGE}
          />
        </group>
        <mesh
          name="Guitar_Holder_2"
          castShadow
          receiveShadow
          geometry={nodes.Guitar_Holder_2.geometry}
          material={materials.MARRON}
          position={[-1.65, 0.56, -1.46]}
          rotation={[Math.PI, -0.15, Math.PI]}
          scale={0.59}
        />
        <group
          name="Black_Guitar"
          position={[-1.66, 0.6, -1.48]}
          rotation={[-3.09, -0.29, 3.12]}
          scale={0.59}
        >
          <mesh
            name="Cube031"
            castShadow
            receiveShadow
            geometry={nodes.Cube031.geometry}
            material={materials.MARRON}
          />
          <mesh
            name="Cube031_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube031_1.geometry}
            material={materials["JAUNE FONCE"]}
          />
          <mesh
            name="Cube031_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube031_2.geometry}
            material={materials.GRIS}
          />
        </group>
        <group
          name="Cube006"
          position={[0.2, 1.24, 1.6]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        >
          <mesh
            name="Cube008"
            castShadow
            receiveShadow
            geometry={nodes.Cube008.geometry}
            material={materials["BOIS DIFFUSEUR"]}
          />
          <mesh
            name="Cube008_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube008_1.geometry}
            material={materials.MARRON}
          />
          <mesh
            name="Cube008_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube008_2.geometry}
            material={materials["BOIS DIFFUSEUR"]}
          />
        </group>
        <group
          name="Cube011"
          position={[0.21, 1.24, 1.04]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        >
          <mesh
            name="Cube014_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube014_1.geometry}
            material={materials["BOIS DIFFUSEUR"]}
          />
          <mesh
            name="Cube014_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube014_2.geometry}
            material={materials.CREME}
          />
          <mesh
            name="Cube014_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube014_3.geometry}
            material={materials.MARRON}
          />
        </group>
        <mesh
          name="Cube009"
          castShadow
          receiveShadow
          geometry={nodes.Cube009.geometry}
          material={materials.MARRON}
          position={[0.25, 0.11, 1.04]}
        />
        <group
          name="Small_Amplifier_3"
          position={[0.62, 0.44, 1.84]}
          rotation={[0, 0.35, 0]}
        >
          <mesh
            name="Cube016"
            castShadow
            receiveShadow
            geometry={nodes.Cube016.geometry}
            material={materials.ORANGE}
          />
          <mesh
            name="Cube016_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube016_1.geometry}
            material={materials["JAUNE PALE"]}
          />
          <mesh
            name="Cube016_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube016_2.geometry}
            material={materials.MARRON}
          />
          <mesh
            name="Cube016_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube016_3.geometry}
            material={materials.ROUGE}
          />
          <mesh
            name="Cube016_4"
            castShadow
            receiveShadow
            geometry={nodes.Cube016_4.geometry}
            material={materials.GRIS}
          />
        </group>
        <group
          name="Orange_Amplifier_1"
          position={[0.62, 0.26, 1.86]}
          rotation={[0, 0.35, 0]}
        >
          <mesh
            name="Cube206"
            castShadow
            receiveShadow
            geometry={nodes.Cube206.geometry}
            material={materials["JAUNE PALE"]}
          />
          <mesh
            name="Cube206_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube206_1.geometry}
            material={materials.ORANGE}
          />
          <mesh
            name="Cube206_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube206_2.geometry}
            material={materials.MARRON}
          />
        </group>
        <group name="PlantG_3_V002" position={[1.62, 0.37, 0.47]}>
          <mesh
            name="Circle043"
            castShadow
            receiveShadow
            geometry={nodes.Circle043.geometry}
            material={materials.VERT}
          />
          <mesh
            name="Circle043_1"
            castShadow
            receiveShadow
            geometry={nodes.Circle043_1.geometry}
            material={materials.CREME}
          />
          <mesh
            name="Circle043_2"
            castShadow
            receiveShadow
            geometry={nodes.Circle043_2.geometry}
            material={materials.MARRON}
          />
        </group>
        <group
          name="Shelf_3_Set001"
          position={[1.48, 1.14, 0.11]}
          rotation={[Math.PI, 0, Math.PI]}
        >
          <mesh
            name="Circle001"
            castShadow
            receiveShadow
            geometry={nodes.Circle001.geometry}
            material={materials.TERRE}
          />
          <mesh
            name="Circle001_1"
            castShadow
            receiveShadow
            geometry={nodes.Circle001_1.geometry}
            material={materials.VERT}
          />
          <mesh
            name="Circle001_2"
            castShadow
            receiveShadow
            geometry={nodes.Circle001_2.geometry}
            material={materials.PIPI}
          />
          <mesh
            name="Circle001_3"
            castShadow
            receiveShadow
            geometry={nodes.Circle001_3.geometry}
            material={materials.CREME}
          />
          <mesh
            name="Circle001_4"
            castShadow
            receiveShadow
            geometry={nodes.Circle001_4.geometry}
            material={materials.ROUGE}
          />
          <mesh
            name="Circle001_5"
            castShadow
            receiveShadow
            geometry={nodes.Circle001_5.geometry}
            material={materials.BLEU}
          />
        </group>
        <group
          name="speaker_high_Left_Body_0"
          position={[0.46, 0.66, 1.39]}
          rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
        >
          <mesh
            name="speaker_high_Left_Body_0_1"
            castShadow
            receiveShadow
            geometry={nodes.speaker_high_Left_Body_0_1.geometry}
            material={materials.MARRON}
          />
          <mesh
            name="speaker_high_Left_Body_0_2"
            castShadow
            receiveShadow
            geometry={nodes.speaker_high_Left_Body_0_2.geometry}
            material={materials["JAUNE PALE"]}
          />
          <group
            name="Cube003"
            position={[0.28, -0.25, 0.3]}
            rotation={[-Math.PI, Math.PI / 6, -Math.PI]}
          >
            <mesh
              name="Cube004_1"
              castShadow
              receiveShadow
              geometry={nodes.Cube004_1.geometry}
              material={materials.BEIGE}
            />
            <mesh
              name="Cube004_2"
              castShadow
              receiveShadow
              geometry={nodes.Cube004_2.geometry}
              material={materials.PIPI}
            />
          </group>
          <group
            name="Level001"
            position={[0.18, 0.12, 0.11]}
            rotation={[1.39, 0.3, -2.59]}
          >
            <mesh
              name="Level001_1"
              castShadow
              receiveShadow
              geometry={nodes.Level001_1.geometry}
              material={materials.GRIS}
            />
            <mesh
              name="Level001_2"
              castShadow
              receiveShadow
              geometry={nodes.Level001_2.geometry}
              material={materials.CREME}
            />
            <mesh
              name="Level001_3"
              castShadow
              receiveShadow
              geometry={nodes.Level001_3.geometry}
              material={materials.MARRON}
            />
          </group>
          <group
            name="Level002"
            position={[0.28, -0.08, 0.38]}
            rotation={[1.39, 0.3, -2.59]}
          >
            <mesh
              name="Level002_1"
              castShadow
              receiveShadow
              geometry={nodes.Level002_1.geometry}
              material={materials.SAUGE}
            />
            <mesh
              name="Level002_2"
              castShadow
              receiveShadow
              geometry={nodes.Level002_2.geometry}
              material={materials.GRIS}
            />
            <mesh
              name="Level002_3"
              castShadow
              receiveShadow
              geometry={nodes.Level002_3.geometry}
              material={materials.BLEU}
            />
          </group>
          <group
            name="speaker_high_right_sponge_0"
            position={[0.66, 0, 0.38]}
            rotation={[0, -Math.PI / 3, 0]}
          >
            <mesh
              name="speaker_high_right_sponge_0_1"
              castShadow
              receiveShadow
              geometry={nodes.speaker_high_right_sponge_0_1.geometry}
              material={materials.MARRON}
            />
            <mesh
              name="speaker_high_right_sponge_0_2"
              castShadow
              receiveShadow
              geometry={nodes.speaker_high_right_sponge_0_2.geometry}
              material={materials["JAUNE PALE"]}
            />
            <mesh
              name="speaker_high_right_sponge_0_3"
              castShadow
              receiveShadow
              geometry={nodes.speaker_high_right_sponge_0_3.geometry}
              material={materials.GRIS}
            />
            <mesh
              name="speaker_high_right_sponge_0_4"
              castShadow
              receiveShadow
              geometry={nodes.speaker_high_right_sponge_0_4.geometry}
              material={materials["VERT FLASH"]}
            />
          </group>
        </group>
        <mesh
          name="Text"
          castShadow
          receiveShadow
          geometry={nodes.Text.geometry}
          material={materials.CREME}
          position={[1.45, 1.17, 0.04]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <group
          name="Stereo_Mixer001"
          position={[0.87, 0.29, 0.26]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="Cube074"
            castShadow
            receiveShadow
            geometry={nodes.Cube074.geometry}
            material={materials.CREME}
          />
          <mesh
            name="Cube074_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube074_1.geometry}
            material={materials.MARRON}
          />
          <mesh
            name="Cube074_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube074_2.geometry}
            material={materials["JAUNE PALE"]}
          />
        </group>
        <group
          name="Chaise"
          position={[1.17, 0.27, 0.89]}
          rotation={[1.85, -0.21, 0.93]}
        >
          <mesh
            name="Level003"
            castShadow
            receiveShadow
            geometry={nodes.Level003.geometry}
            material={materials.GRIS}
          />
          <mesh
            name="Level003_1"
            castShadow
            receiveShadow
            geometry={nodes.Level003_1.geometry}
            material={materials.MARRON}
          />
        </group>
        <mesh
          name="Circle"
          castShadow
          receiveShadow
          geometry={nodes.Circle.geometry}
          material={materials.SAUGE}
          position={[1.12, 0.13, 1.2]}
        />
        <group
          name="Cube010"
          position={[-1, 0.97, 0.01]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.12, 0.26, 0.53]}
        >
          <mesh
            name="Cube029"
            castShadow
            receiveShadow
            geometry={nodes.Cube029.geometry}
            material={materials.GRIS}
          />
          <mesh
            name="Cube029_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube029_1.geometry}
            material={materials.GRIS}
          />
        </group>
        <mesh
          name="Text001"
          castShadow
          receiveShadow
          geometry={nodes.Text001.geometry}
          material={materials.CREME}
          position={[-0.25, 0.36, 1.41]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={0.24}
        />
        <group name="Mixing_Table" position={[-1.03, 0.5, 0.64]} scale={0.56}>
          <mesh
            name="Cube054"
            castShadow
            receiveShadow
            geometry={nodes.Cube054.geometry}
            material={materials["JAUNE PALE"]}
          />
          <mesh
            name="Cube054_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube054_1.geometry}
            material={materials.MARRON}
          />
          <mesh
            name="Cube054_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube054_2.geometry}
            material={materials.BLEU}
          />
          <mesh
            name="Cube054_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube054_3.geometry}
            material={materials.GRIS}
          />
          <mesh
            name="Cube054_4"
            castShadow
            receiveShadow
            geometry={nodes.Cube054_4.geometry}
            material={materials["ROUGE FLASH"]}
          />
          <mesh
            name="Cube054_5"
            castShadow
            receiveShadow
            geometry={nodes.Cube054_5.geometry}
            material={materials["VERT FLASH"]}
          />
        </group>
        <group
          name="Speaker_2"
          position={[-1.64, 0.68, 0.28]}
          rotation={[0, -0.45, 0]}
          scale={1.05}
        >
          <mesh
            name="Cube047"
            castShadow
            receiveShadow
            geometry={nodes.Cube047.geometry}
            material={materials.MARRON}
          />
          <mesh
            name="Cube047_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube047_1.geometry}
            material={materials["JAUNE FONCE"]}
          />
        </group>
        <mesh
          name="Cube014"
          castShadow
          receiveShadow
          geometry={nodes.Cube014.geometry}
          material={materials["BOIS INTER"]}
          position={[-1.72, 0.11, 1.04]}
          scale={[1, 0.11, 1]}
        />
        <group
          name="Chair_1"
          position={[-0.82, 0.33, 1.35]}
          rotation={[3.14, -0.39, -3.14]}
          scale={0.6}
        >
          <mesh
            name="Cube035_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube035_1.geometry}
            material={materials["JAUNE PALE"]}
          />
          <mesh
            name="Cube035_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube035_2.geometry}
            material={materials.GRIS}
          />
          <mesh
            name="Cube035_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube035_3.geometry}
            material={materials["JAUNE FONCE"]}
          />
        </group>
        <group
          name="Cube023"
          position={[-1.31, 1.71, 0.82]}
          rotation={[Math.PI, 0, 0]}
          scale={0.72}
        >
          <mesh
            name="Cube039_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube039_1.geometry}
            material={materials["BOIS DIFFUSEUR"]}
          />
          <mesh
            name="Cube039_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube039_2.geometry}
            material={materials.MARRON}
          />
          <mesh
            name="Cube039_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube039_3.geometry}
            material={materials.MARRON}
          />
        </group>
        <group
          name="Cube024"
          position={[-1.31, 1.48, 0.11]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.84, 0.85, 0.84]}
        >
          <mesh
            name="Cube040_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube040_1.geometry}
            material={materials["BOIS DIFFUSEUR"]}
          />
          <mesh
            name="Cube040_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube040_2.geometry}
            material={materials.CREME}
          />
          <mesh
            name="Cube040_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube040_3.geometry}
            material={materials.MARRON}
          />
        </group>
        <group
          name="Cube025"
          position={[-0.68, 1.48, 0.11]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.84, 0.85, 0.84]}
        >
          <mesh
            name="Cube041"
            castShadow
            receiveShadow
            geometry={nodes.Cube041.geometry}
            material={materials["BOIS DIFFUSEUR"]}
          />
          <mesh
            name="Cube041_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube041_1.geometry}
            material={materials.CREME}
          />
          <mesh
            name="Cube041_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube041_2.geometry}
            material={materials.MARRON}
          />
        </group>
        <group
          name="Cube026"
          position={[-0.27, 1.1, 0.82]}
          rotation={[Math.PI / 2, 0, 1.57]}
          scale={[0.84, 0.85, 0.84]}
        >
          <mesh
            name="Cube006_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube006_1.geometry}
            material={materials["BOIS DIFFUSEUR"]}
          />
          <mesh
            name="Cube006_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube006_2.geometry}
            material={materials.CREME}
          />
          <mesh
            name="Cube006_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube006_3.geometry}
            material={materials.MARRON}
          />
        </group>
        <group
          name="Cube027"
          position={[-0.23, 1.1, 1.45]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.72}
        >
          <mesh
            name="Cube012_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube012_1.geometry}
            material={materials["BOIS DIFFUSEUR"]}
          />
          <mesh
            name="Cube012_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube012_2.geometry}
            material={materials.MARRON}
          />
        </group>
        <group
          name="Speaker_2001"
          position={[-0.34, 0.68, 0.27]}
          rotation={[0, -1.45, 0]}
          scale={1.05}
        >
          <mesh
            name="Cube007"
            castShadow
            receiveShadow
            geometry={nodes.Cube007.geometry}
            material={materials.MARRON}
          />
          <mesh
            name="Cube007_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube007_1.geometry}
            material={materials["JAUNE FONCE"]}
          />
        </group>
        <mesh
          name="Cube042"
          castShadow
          receiveShadow
          geometry={nodes.Cube042.geometry}
          material={materials["BOIS CLAIR"]}
          position={[-0.19, 0.95, 2.01]}
        />
        <group
          name="Armchair_3_Gray002"
          position={[1.28, 0.28, -1.73]}
          rotation={[0, -0.98, 0]}
          scale={0.37}
        >
          <mesh
            name="Plane088"
            castShadow
            receiveShadow
            geometry={nodes.Plane088.geometry}
            material={materials.CREME}
          />
          <mesh
            name="Plane088_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane088_1.geometry}
            material={materials.ORANGE}
          />
        </group>
        <group
          name="Sofa_4_Gray_Set"
          position={[1.6, 0.36, -1.03]}
          rotation={[0, -1.56, 0]}
          scale={0.37}
        >
          <mesh
            name="Plane001"
            castShadow
            receiveShadow
            geometry={nodes.Plane001.geometry}
            material={materials.GRIS}
          />
          <mesh
            name="Plane001_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane001_1.geometry}
            material={materials.CREME}
          />
          <mesh
            name="Plane001_2"
            castShadow
            receiveShadow
            geometry={nodes.Plane001_2.geometry}
            material={materials.ORANGE}
          />
        </group>
        <mesh
          name="Object_17"
          castShadow
          receiveShadow
          geometry={nodes.Object_17.geometry}
          material={materials.MARRON}
          position={[1.61, 0.5, -1.09]}
          rotation={[-1.62, 0.32, -1.35]}
          scale={0.01}
        />
        <group
          name="Armchair_3_Gray,001"
          position={[1.23, 0.28, -0.32]}
          rotation={[Math.PI, -0.84, Math.PI]}
          scale={0.37}
        >
          <mesh
            name="Plane090"
            castShadow
            receiveShadow
            geometry={nodes.Plane090.geometry}
            material={materials.CREME}
          />
          <mesh
            name="Plane090_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane090_1.geometry}
            material={materials.ORANGE}
          />
        </group>
        <group name="Shelf_2_Set" position={[0.59, 0.5, -0.11]} scale={0.27}>
          <mesh
            name="Plane084"
            castShadow
            receiveShadow
            geometry={nodes.Plane084.geometry}
            material={materials.GRIS}
          />
          <mesh
            name="Plane084_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane084_1.geometry}
            material={materials.CREME}
          />
          <mesh
            name="Plane084_2"
            castShadow
            receiveShadow
            geometry={nodes.Plane084_2.geometry}
            material={materials.ORANGE}
          />
          <mesh
            name="Plane084_3"
            castShadow
            receiveShadow
            geometry={nodes.Plane084_3.geometry}
            material={materials.BLEU}
          />
          <mesh
            name="Plane084_4"
            castShadow
            receiveShadow
            geometry={nodes.Plane084_4.geometry}
            material={materials["JAUNE FONCE"]}
          />
          <mesh
            name="Plane084_5"
            castShadow
            receiveShadow
            geometry={nodes.Plane084_5.geometry}
            material={materials.VERT}
          />
          <mesh
            name="Plane084_6"
            castShadow
            receiveShadow
            geometry={nodes.Plane084_6.geometry}
            material={materials.ROUGE}
          />
        </group>
        <group
          name="Table_1001"
          position={[0.94, 0.24, -1.07]}
          rotation={[0, -1.15, 0]}
          scale={0.41}
        >
          <mesh
            name="Plane043"
            castShadow
            receiveShadow
            geometry={nodes.Plane043.geometry}
            material={materials.MARRON}
          />
          <mesh
            name="Plane043_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane043_1.geometry}
            material={materials.GRIS}
          />
          <mesh
            name="Plane043_2"
            castShadow
            receiveShadow
            geometry={nodes.Plane043_2.geometry}
            material={materials.BLEU}
          />
          <mesh
            name="Plane043_3"
            castShadow
            receiveShadow
            geometry={nodes.Plane043_3.geometry}
            material={materials.CREME}
          />
        </group>
        <group
          name="Furniture_1_Set"
          position={[0.28, 0.45, -1.05]}
          rotation={[0, -1.57, 0]}
          scale={0.5}
        >
          <mesh
            name="Cube061"
            castShadow
            receiveShadow
            geometry={nodes.Cube061.geometry}
            material={materials.GRIS}
          />
          <mesh
            name="Cube061_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube061_1.geometry}
            material={materials.CREME}
          />
          <mesh
            name="Cube061_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube061_2.geometry}
            material={materials.NOIR}
          />
        </group>
        <group
          name="Cube021"
          position={[0.16, 1.13, -1.04]}
          scale={[0.01, 0.42, 0.73]}
        >
          <mesh
            name="Cube037_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube037_1.geometry}
            material={materials.MARRON}
          />
          <mesh
            name="Cube037_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube037_2.geometry}
            material={materials.CREME}
          />
        </group>
        <mesh
          name="Cube017"
          castShadow
          receiveShadow
          geometry={nodes.Cube017.geometry}
          material={materials.GRIS}
          position={[0.17, 1.56, -1.04]}
          scale={[0.02, 0.02, 0.8]}
        />
        <mesh
          name="Text003"
          castShadow
          receiveShadow
          geometry={nodes.Text003.geometry}
          material={materials.CREME}
          position={[0.64, 1.38, -0.05]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={0.24}
        />
        <mesh
          name="Cube012"
          castShadow
          receiveShadow
          geometry={nodes.Cube012.geometry}
          material={materials.CREME}
          position={[0.25, 0.11, -1.04]}
          scale={[1, 0.11, 1]}
        />
        <group
          name="Cube037"
          position={[1.4, 1.39, -0.09]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={0.72}
        >
          <mesh
            name="Cube048_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube048_1.geometry}
            material={materials["BOIS DIFFUSEUR"]}
          />
          <mesh
            name="Cube048_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube048_2.geometry}
            material={materials.MARRON}
          />
          <mesh
            name="Cube048_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube048_3.geometry}
            material={materials.MARRON}
          />
        </group>
        <group
          name="Cube040"
          position={[1.4, 0.85, -0.09]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={0.72}
        >
          <mesh
            name="Cube065"
            castShadow
            receiveShadow
            geometry={nodes.Cube065.geometry}
            material={materials["BOIS DIFFUSEUR"]}
          />
          <mesh
            name="Cube065_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube065_1.geometry}
            material={materials.MARRON}
          />
          <mesh
            name="Cube065_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube065_2.geometry}
            material={materials.MARRON}
          />
        </group>
        <group
          name="sabre"
          position={[1.03, 0.32, -0.88]}
          rotation={[-Math.PI, 0, 0]}
          scale={0}
        >
          <mesh
            name="SABER_02_-_Default_0"
            castShadow
            receiveShadow
            geometry={nodes["SABER_02_-_Default_0"].geometry}
            material={materials.GRIS}
          />
          <mesh
            name="SABER_02_-_Default_0_1"
            castShadow
            receiveShadow
            geometry={nodes["SABER_02_-_Default_0_1"].geometry}
            material={materials.MARRON}
          />
          <mesh
            name="SABER_02_-_Default_0_2"
            castShadow
            receiveShadow
            geometry={nodes["SABER_02_-_Default_0_2"].geometry}
            material={materials["ROUGE FLASH"]}
          />
          <mesh
            name="SABER_02_-_Default_0_3"
            castShadow
            receiveShadow
            geometry={nodes["SABER_02_-_Default_0_3"].geometry}
            material={materials.NOIR}
          />
        </group>
        <mesh
          name="TargetCam"
          castShadow
          receiveShadow
          geometry={nodes.TargetCam.geometry}
          material={nodes.TargetCam.material}
          position={[0, 0.77, 0]}
          scale={0.02}
        />

        <mesh
          name="Cube005"
          castShadow
          receiveShadow
          geometry={nodes.Cube005.geometry}
          material={nodes.Cube005.material}
          position={[3.41, 1.05, 3.9]}
          rotation={[1.53, 0.04, -0.72]}
          scale={0.06}
        />
        <mesh
          name="ParentCam"
          castShadow
          receiveShadow
          geometry={nodes.ParentCam.geometry}
          material={nodes.ParentCam.material}
          position={[3.41, 1.05, 3.9]}
          rotation={[1.53, 0.04, -0.72]}
          scale={0.11}
        >

        </mesh>
        <mesh
          name="BackStage_Curtains001"
          castShadow
          receiveShadow
          geometry={nodes.BackStage_Curtains001.geometry}
          material={materials.SAUMONS}
          position={[-1.01, 0.84, -0.07]}
          rotation={[1.32, 1.56, -1.28]}
          scale={[0.5, 0.5, 0.52]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/customers_coloriage_reduction.glb");
